# $FreeBSD$
# All the dts files for allwinner systems we support.
DTS=	\
	bananapi.dts \
	cubieboard.dts \
	cubieboard2.dts \
	olimex-a20-som-evb.dts \
	olinuxino-lime.dts \
	sun6i-a31s-sinovoip-bpi-m2.dts

.include <bsd.dtb.mk>
